# Generated by Django 5.1.1 on 2024-10-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_allcategory_delete_incomeexpensecategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
